version: '3'
services:
    graphdb:
        build:
            context: ./graphdb
        ports:
            - 7200:7200
        environment:
            - GDB_HEAP_SIZE=2g
            - GDB_MIN_MEM=1g
            - GDB_MAX_MEM=2g      
    triplifier:
        image: registry.gitlab.com/um-cds/fair/tools/triplifier:1.1.0
        hostname: triplifier.local
        # environment:
            # - SLEEPTIME=360
        volumes:
            - ./triplifier.props:/triplifier.properties
            - ./triplifier_data:/data
